name: "Commotion Wireless"
description: "Commotion is an open-source communication tool that uses mobile phones, computers, and other wireless devices to create decentralized mesh networks."

encoding: utf-8

url: "staging.commotionwireless.net"
port: 80
piwik:
  base_url: piwik.opentechinstitute.org
  site_id: 1

permalink: /blog/:year/:month/:day/:title
pagination: 3
